---
- name: "Generate Mario's Password"
  command: "/usr/sbin/slappasswd -s mariopw"
  register: slapd_mario_pw_hash
  changed_when: false

- name: "Generate Maria's Password"
  command: "/usr/sbin/slappasswd -s mariapw"
  register: slapd_maria_pw_hash
  changed_when: false

- name: "Generate Pino's Password"
  command: "/usr/sbin/slappasswd -s pinopw"
  register: slapd_pino_pw_hash
  changed_when: false

- name: "Generate Pina's Password"
  command: "/usr/sbin/slappasswd -s pinapw"
  register: slapd_pina_pw_hash
  changed_when: false

- ldap_entry:
    dn: "uid=mario,ou=people,dc=example,dc=org"
    objectClass:
      - inetOrgPerson
      - eduPerson
      - schacLinkageIdentifiers
      - schacEntryMetadata
    attributes:
      uid: "mario"
      sn: "Rossi"
      givenName: "Mario"
      cn: "Mario Rossi"
      mail: "mario.rossi@example.org"
      eduPersonAffiliation: "member"
      employeeNumber: "A-1002"
      userPassword: "mariopw2018"

- ldap_attr:
    dn: "uid=mario,ou=people,dc=example,dc=org"
    name: eduPersonAffiliation
    values:
     - "member"
     - "staff"
    state: present

- ldap_entry:
    dn: "uid=maria,ou=people,dc=example,dc=org"
    objectClass:
      - inetOrgPerson
      - eduPerson
      - schacLinkageIdentifiers
      - schacEntryMetadata
    attributes:
      uid: "maria"
      sn: "Verdi"
      givenName: "Maria"
      cn: "Maria Verdi"
      mail: "maria.verdi@example.org"
      eduPersonAffiliation: "member"
      employeeNumber: "A-1001"
      userPassword: "mariapw2018"

- ldap_attr:
    dn: "uid=maria,ou=people,dc=example,dc=org"
    name: eduPersonAffiliation
    values:
     - "member"
     - "student"
    state: present

- ldap_entry:
    dn: "uid=pino,ou=people,dc=example,dc=org"
    objectClass:
      - inetOrgPerson
      - eduPerson
      - schacLinkageIdentifiers
      - schacEntryMetadata
    attributes:
      uid: "pino"
      sn: "Verdi"
      givenName: "Pino"
      cn: "Pino Verdi"
      mail: "pino.verdi@example.org"
      eduPersonAffiliation: "member"
      employeeNumber: "A-1003"
      userPassword: "pinopw2018"

- ldap_attr:
    dn: "uid=pino,ou=people,dc=example,dc=org"
    name: eduPersonAffiliation
    values:
     - "member"
     - "staff"
    state: present

- ldap_entry:
    dn: "uid=pina,ou=people,dc=example,dc=org"
    objectClass:
      - inetOrgPerson
      - eduPerson
      - schacLinkageIdentifiers
      - schacEntryMetadata
    attributes:
      uid: "pina"
      sn: "Verdi"
      givenName: "Pina"
      cn: "Pina Verdi"
      mail: "pina.verdi@example.org"
      eduPersonAffiliation: "member"
      employeeNumber: "A-1004"
      userPassword: "pinapw2018"

- ldap_attr:
    dn: "uid=pina,ou=people,dc=example,dc=org"
    name: eduPersonAffiliation
    values:
     - "member"
     - "faculty"
    state: present

