---

- ldap_entry:
    dn: "ou={{ item.name }},dc=example,dc=org"
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: "{{ item.ou }}"
      description: "Example ORG {{ item.name }}"
  with_items:
   - { name: "people", ou: "People" }
   - { name: "groups", ou: "Groups" }
   - { name: "system", ou: "System" }
   - { name: "policies", ou: "Policies" }
