---
# tasks for openLDAP Installation
- name: "Install 'debconf-utils' and 'python-ldap' packages"
  apt:
   name: "{{ item }}"
   state: latest
   install_recommends: "no"
  with_items:
   - debconf-utils
   - python-ldap

- name: "Check if debconf-get-selections has parameters for unattended OpenLDAP installation and store the result on 'debconf' ansible variable"
  shell: (debconf-get-selections | grep -q -s slapd); echo $?
  register: debconf
  ignore_errors: yes
  changed_when: false

- name: "Set OpenLDAP unattended installation parameters"
  debconf:
    name: "slapd"
    question: "{{ item.key }}"
    vtype: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: slapd/password1
      type: password
      value: "{{ ldap_pw | default('') }}"
    - key: slapd/password2
      type: password
      value: "{{ ldap_pw | default('') }}"
    - key: slapd/move_old_database
      type: boolean
      value: true
    - key: slapd/domain
      type: string
      value: "{{ domain | default('') }}"
    - key: shared/organization
      type: string
      value: "{{ ldap_org | default('Example Org') }}"
    - key: slapd/no_configuration
      type: boolean
      value: false
    - key: slapd/purge_database
      type: boolean
      value: false
    - key: slapd/allow_ldap_v2
      type: boolean
      value: false
    - key: slapd/backend
      type: select
      value: MDB
  when: debconf.stdout == "1"
  
- name: "Install OpenLDAP and its utilities"
  apt:
   name: "{{ item }}"
   state: latest
   install_recommends: "no"
  with_items:
    - slapd
    - ldap-utils
