---
- name: Install IdP Course VM
  hosts: all
  become: yes
  vars:
    domain: example.org
    cert_path: /etc/ssl/certs
    java_home: /usr/lib/jvm/default-jave/jre
    idp_dl_url: https://shibboleth.net/downloads/identity-provider/3.3.2/shibboleth-identity-provider-3.3.2.tar.gz
    idp_fqdn: idp.example.org
    idp_path: /opt/shibboleth-idp
    sp_fqdn: sp.example.org
    ldap_pw: password
    idp_pw: password
    mysql_pw: password
    idpdb_user: shibboleth
    idpdb_pw: password
  roles:
    - common
    - jdk
    - jetty
    - openldap
    - apache2
    - mysql
#    - shib3idp
#    - mod-shib2

