---
# tasks file for apache
- name: "Add Apache user 'www-data' to 'ssl-cert' group"
  user:
   name: "www-data"
   groups: "ssl-cert"

- name: "Be sure to have Apache modules alias, SSL, include, negotiation, headers and Proxy enabled"
  apache2_module:
   name: "{{ item }}"
   state: present
  with_items:
   - alias
   - ssl
   - include
   - negotiation
   - headers
   - proxy_http
  notify:
   - "Restart Apache"

- name: "Modify and Enable default SSL Apache configuration"
  template:
   src: default-ssl.conf.j2
   dest: /etc/apache2/sites-enabled/default-ssl.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Enable the redirection to HTTPS from all HTTP URL"
  template:
   src: default.conf.j2
   dest: /etc/apache2/sites-enabled/000-default.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Localize Apache error pages"
  copy:
   src: files/localized-error-pages.conf
   dest: /etc/apache2/conf-enabled/localized-error-pages.conf
   owner: "root"
   group: "root"
   mode: "0644"
  notify:
   - "Restart Apache"

- name: "Dirs for IdP and SP Virtualhosts"
  file: 
   name: "{{ item }}"
   state: directory
  with_items:
    - /var/log/apache2/idp.example.org
    - /var/log/apache2/sp.example.org
    - /var/www/html/sp.example.org
    - /var/www/html/sp.example.org/secure
    - /var/www/html/idp.example.org
    - /var/www/css

- name: "Install IdP Index file"
  copy:
   src: files/idp-index.html
   dest: /var/www/html/idp.example.org/index.html

- name: "Site content for sp.example.org"
  copy:
   src: roles/apache2/files/sp.example.org/
   dest: /var/www/html/sp.example.org/

- name: "Install Bootstrap Min CSS"
  copy:
   src: files/bootstrap.min.css
   dest: /var/www/css/bootstrap.min.css
