- name: Stat Shibboleth IdP tarball in /opt 
  stat: 
   path: /opt/shibboleth-identity-provider-3.3.2.tar.gz
  register: shib_tarball

- name: Download Shibboleth IdP
  get_url: 
   url: "{{ idp_dl_url }}" 
   dest: /opt
  when: shib_tarball.stat.exists == False

- name: Stat Shibboleth IdP source dir in /opt 
  stat: 
   path: /opt/shibboleth-identity-provider-3.3.2
  register: shib_dir_source
  
- name: Unarchive Shibboleth IdP
  unarchive: 
   src: /opt/shibboleth-identity-provider-3.3.2.tar.gz 
   dest: /opt
  when: shib_dir_source.stat.exists == False and pre_t is defined and pre_t > 1 

- name: Cleanup Shibboleth IdP Install
  file: 
   path: /opt/shibboleth-idp 
   state: absent
  when: "cleanup is defined"

- name: Stat Shibboleth IdP dest dir in /opt
  stat: 
   path: /opt/shibboleth-idp/metadata
  register: shib_dir_dest

- name: Copy template configuration for ldap.properties
  copy: 
    src: files/ldap.properties-corso
    dest: "{{ idp_path }}/conf/ldap.properties"
  when: pre_t is defined and pre_t == 1

- name: Copy template configuration saml-nameid.properties
  copy: 
    src: roles/shib3idp/files/saml-nameid.properties-corso
    dest: "{{ idp_path }}/conf/saml-nameid.properties"
  when: pre_t is defined and pre_t == 1
  
- name: Copy template configuration global.xml
  template: 
    src: roles/shib3idp/templates/global.xml-corso
    dest: "{{ idp_path }}/conf/global.xml"
  when: pre_t is defined and pre_t == 1

- name: Prepare properties for Shibboleth IdP install
  template: 
    src: roles/shib3idp/templates/shib-install.properties 
    dest: /tmp/shib-install.properties
  when: pre_t is defined and pre_t > 1 

- name: "Put the JSTL libraries, needed for Shibboleth IdP Status page, in the right position"
  copy:
   src: "files/jstl-1.2.jar"
   dest: "/opt/shibboleth-identity-provider-3.3.2/webapp/WEB-INF/lib/jstl-1.2.jar"
   owner: "root"
   group: "root"
   mode: 0644
  when: pre_t is defined and pre_t > 1 

- name: "Create link for commons-dbcp, commons-pool and mysql JAR files used by Shibboleth IdP"
  file:
   src: "{{ item.src }}" 
   dest: "{{ item.dest }}"
   owner: "jetty"
   group: "jetty"
   state: link
  with_items:
   - { src: '/usr/share/java/commons-dbcp.jar' ,dest: "/opt/shibboleth-identity-provider-3.3.2/webapp/WEB-INF/lib/commons-dbcp.jar" }
   - { src: '/usr/share/java/commons-pool.jar' ,dest: "/opt/shibboleth-identity-provider-3.3.2/webapp/WEB-INF/lib/commons-pool.jar" }
   - { src: '/usr/share/java/mysql.jar' ,dest: "/opt/shibboleth-identity-provider-3.3.2/webapp/WEB-INF/lib/mysql-connector-java.jar" }
  when: pre_t is defined and pre_t > 1 

- name: Install Shibboleth Idp
  environment: 
    JAVA_HOME: "{{ java_home }}"
  command: |
    /opt/shibboleth-identity-provider-3.3.2/bin/install.sh \
    -Didp.sealer.password={{ idp_pw }} \
    -Didp.keystore.password={{ idp_pw }} \
    -Didp.scope={{ domain }} \
    -Didp.src.dir=/opt/shibboleth-identity-provider-3.3.2 \
    -Didp.host.name={{ idp_fqdn }} \
    -Didp.target.dir=/opt/shibboleth-idp \
    -Didp.merge.properties=/tmp/shib-install.properties
  when: shib_dir_dest.stat.exists == False and pre_t is defined and pre_t > 1 
  
- name: Jetty user for idp dirs
  file: 
   name: "{{ item }}" 
   owner: jetty
   recurse: yes
  with_items:
    - "{{ idp_path }}/conf"
    - "{{ idp_path }}/logs"
    - "{{ idp_path }}/metadata"
    - "{{ idp_path }}/credentials"
    - "{{ idp_path }}/system"
    - "{{ idp_path }}/war"
  when: pre_t is defined and pre_t > 1 
  
- name: Install the IdP WAR
  copy:
    src: files/idp.xml 
    dest: /opt/jetty/webapps/idp.xml
  when: pre_t is defined and pre_t > 1 

- name: Generate salt for persistentId generator
  shell: openssl rand -base64 36
  register: persId_salt
  when: pre_t is defined and pre_t > 1 
  
- name: Configure LDAP Auth
  copy: 
    src: roles/shib3idp/files/ldap.properties 
    dest: "{{ idp_path }}/conf/ldap.properties" 
  when: pre_t is defined and pre_t > 1 
    
- name: Configure Enhanced Logging
  copy: 
    src: roles/shib3idp/files/logback.xml 
    dest: "{{ idp_path }}/conf/logback.xml"
  when: pre_t is defined and pre_t > 1 

- name: Configure saml-nameid.properties (dataStore and persistentId)
  template: 
    src: roles/shib3idp/templates/saml-nameid.properties 
    dest: "{{ idp_path }}/conf/saml-nameid.properties" 
  when: pre_t is defined and pre_t > 1 

- name: Configure saml-nameid.xml (persistentId)
  copy: 
    src: roles/shib3idp/files/saml-nameid.xml
    dest:  "{{ idp_path }}/conf/saml-nameid.xml"
  when: pre_t is defined and pre_t > 1 

- name: Configure relying-party.xml (persistentId)
  copy:
    src: roles/shib3idp/files/relying-party.xml
    dest:  "{{ idp_path }}/conf/relying-party.xml"
  when: pre_t is defined and pre_t > 1 

- name: Configure global.xml (dataStore and persistentId)
  template:
    src: roles/shib3idp/templates/global.xml
    dest:  "{{ idp_path }}/conf/global.xml"
  when: pre_t is defined and pre_t > 1 

- name: Configure IdP attribute-filter.xml 
  copy: 
    src: roles/shib3idp/files/attribute-filter.xml
    dest: "{{ idp_path }}/conf/attribute-filter.xml"
  when: pre_t is defined and pre_t > 2

- name: Copy configured attribute-resolver-full.xml in attribute-resolver.xml
  copy: 
    src: roles/shib3idp/files/attribute-resolver-full.xml
    dest: "{{ idp_path }}/conf/attribute-resolver.xml"
  when: pre_t is defined and pre_t > 2 

- name: Add attribute-resolver-full.xml to services.xml
  copy: 
    src: roles/shib3idp/files/services.xml
    dest: "{{ idp_path }}/conf/services.xml"
  when: pre_t is defined and pre_t > 2 

- name: Copy scripts in /opt/shibboleth-idp/conf
  copy:
    src: roles/shib3idp/files/scripts
    dest: "{{ idp_path }}/conf/"
    owner: jetty

- name: Add IdP attribute-resolver-myRdbms.xml-template
  copy: 
    src: roles/shib3idp/files/attribute-resolver-myRdbms.xml-template
    dest: "{{ idp_path }}/conf/attribute-resolver-myRdbms.xml"
  when: pre_t is defined and pre_t > 2
    
- name: Configure IdP attribute-filter.xml pre_t3 and pre_t4
  copy: 
    src: roles/shib3idp/files/attribute-filter.xml-pre_t4
    dest: "{{ idp_path }}/conf/attribute-filter.xml"
  when: pre_t is defined and pre_t > 3

- name: Configure IdP attribute-resolver.xml-pre_t4
  copy: 
    src: roles/shib3idp/files/attribute-resolver.xml-pre_t4
    dest: "{{ idp_path }}/conf/attribute-resolver.xml"
  when: pre_t is defined and pre_t > 3 

- name: Remove attribute-resolver-full.xml from services.xml
  copy: 
    src: roles/shib3idp/files/services.xml-pre_t4
    dest: "{{ idp_path }}/conf/services.xml"
  when: pre_t is defined and pre_t > 3

- name: Configure IdP attribute-resolver.xml-pre_t5
  copy: 
    src: roles/shib3idp/files/attribute-resolver.xml-pre_t5
    dest: "{{ idp_path }}/conf/attribute-resolver.xml"
  when: pre_t is defined and pre_t > 4
  
- name: "Restart Jetty"
  become: yes
  become_method: sudo
  systemd:
   name: jetty
   daemon-reload: True
   state: restarted
  when: pre_t is defined and pre_t > 1
  
