---
# tasks file for mysql
- name: "Install 'debconf-utils' package"
  apt:
   name: "debconf-utils"
   state: latest
   install_recommends: "no"
  tags: mysql

- name: "Check if debconf-get-selections has parameters for unattended mysql installation and store the result on 'debconf' ansible variable"
  shell: (debconf-get-selections | grep -q -s mysql-server); echo $?
  register: debconf
  ignore_errors: yes
  changed_when: false
  tags: mysql 

- name: "Set MYSQL unattented installation debconf's parameters"
  debconf:
    name: "mysql-server"
    question: "{{ item.question }}"
    vtype: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - question: mysql-server/root_password
      type: password
      value: "{{ mysql_pw }}"
    - question: mysql-server/root_password_again
      type: password
      value: "{{ mysql_pw }}"
  when: debconf.stdout == "1"
  tags: mysql

- name: "Install Mysql server and needed libraries"
  apt:
   name: "{{ item }}"
   state: latest
   install_recommends: "no"
  with_items:
   - python-mysqldb
   - mysql-server
   - libmysql-java
   - libcommons-dbcp-java
   - libcommons-pool-java
   - libjstl1.1-java
  tags: mysql

- name: "Configure .my.cnf file for a simple MySQL authentication"
  template: 
    src: "root.cnf.j2" 
    dest: "~/.my.cnf"
    mode: 0600
  tags: mysql

- name: "Assign the right privileges to the /tmp directory"
  file:
    path: "/tmp"
    state: directory
    mode: "u+rwx,g+rwx,o+rwt"
  tags: mysql

- name: "Start MySQL service"
  systemd:
    name: mysql
    daemon-reload: True
    state: started
    enabled: True
  tags: mysql

- name: "Be sure that all root accounts receive the root password for database"
  mysql_user: 
   name: "root" 
   host: "{{ item }}" 
   password: "{{ mysql_pw }}"
   state: present
  with_items:
     - "idp.example.org"
     - "sp.example.org"
     - 127.0.0.1
     - ::1
     - localhost
  tags: mysql

- name: "Put the Shibboleth Identity Provider persistent-id database structure file in the right position"
  copy:
   src: "files/shibboleth.sql"
   dest: "/root/shibboleth.sql"
   owner: "root"
   group: "root"
   mode: "0600"
  tags: mysql

- name: "Put the 'insert-ruoliorganizzativi.sql' file in the right position"
  copy:
   src: "files/insert-ruoliorganizzativi.sql"
   dest: "/root/insert-ruoliorganizzativi.sql"
   owner: "root"
   group: "root"
   mode: "0600"
  tags: mysql

- name: "Check the existance of 'shibboleth' database"
  command: mysql -u root -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='shibboleth'"
  register: shib_db
  changed_when: false
  tags: mysql

- name: "Create 'shibboleth' database"
  mysql_db:
   encoding: "utf8"
   state: import
   name: all
   target: "/root/shibboleth.sql"
  when: "shib_db.stdout != 'shibboleth' and cleanup is not defined"
  tags: mysql

- name: "Create 'RuoliOrganizzativi' table and insert some datas on it"
  mysql_db:
   encoding: "utf8"
   state: import
   name: all
   target: "/root/insert-ruoliorganizzativi.sql"
  when: "shib_db.stdout != 'shibboleth' and cleanup is not defined"
  tags: mysql

