- name: "Configure /etc/hosts"
  template: 
   src: "roles/common/templates/hosts"
   dest: "/etc/hosts"

- name: "Configure /etc/environment"
  template: 
   src: "roles/common/templates/environment"
   dest: "/etc/environment"

#- name: "Add GARR apt sources"
#  template: 
#   src: "roles/common/templates/sources.list"
#   dest: "/etc/apt/sources.list"

- name: "Uninstall slapd"
  apt: 
   name: "slapd" 
   state: "absent" 
   purge: "yes"
  when: "cleanup is defined"

- name: "Remove /var/lib/ldap"
  file: 
   path: "/var/lib/ldap" 
   state: "absent"
  when: "cleanup is defined"

- name: "Uninstall libapache2-mod-shib2"
  apt: 
   name: "libapache2-mod-shib2" 
   state: "absent"
   purge: "yes"
  when: "cleanup is defined"

- name: "Remove /etc/shibboleth dir"
  file: 
   path: "/etc/shibboleth"
   state: "absent"
  when: "cleanup is defined"

- name: "Remove /opt/shibboleth-idp dir"
  file: 
   path: "/opt/shibboleth-idp"
   state: "absent"
  when: "cleanup is defined"

- name: "Install apt packages"
  apt: 
   name: "{{ item }}"
   update_cache: "yes"
   state: "latest"
  with_items:
    - html2text
    - vim
    - ntp
    - libmysql-java
    - ca-certificates
    - ssl-cert
    - openssl
  tags: online

- name: "Install CA Certificate"
  copy: 
   src: "roles/common/files/cacert.pem"
   dest: "/etc/ssl/certs/cacert.pem"

- name: "Install CA Key"
  copy: 
   src: "roles/common/files/cakey.pem"
   dest: "/etc/ssl/private" 
   mode: "0600"

- name: "Install IdP Certificate"
  copy: 
   src: "roles/common/files/idp.example.org-cert.pem"
   dest: "/etc/ssl/certs/idp.example.org-cert.pem"

- name: "Install IdP Key"
  copy: 
   src: "roles/common/files/idp.example.org-key.pem" 
   dest: "/etc/ssl/private/idp.example.org-key.pem" 
   group: "ssl-cert" 
   mode: "0640"

- name: "Install SP Certificate"
  copy: 
   src: "roles/common/files/sp.example.org-cert.pem" 
   dest: "/etc/ssl/certs/sp.example.org-cert.pem"

- name: "Install SP Key"
  copy: 
   src: "roles/common/files/sp.example.org-key.pem" 
   dest: "/etc/ssl/private/sp.example.org-key.pem" 
   group: "ssl-cert"
   mode: "0640"
