- name: "Configure /etc/hosts"
  template: 
   src: "roles/common/templates/hosts"
   dest: "/etc/hosts"

- name: "Configure /etc/environment"
  template: 
   src: "roles/common/templates/environment"
   dest: "/etc/environment"

- name: "Set the hostname 'idp'"
  command: "hostnamectl set-hostname idp"
  changed_when: false

- name: "Add GARR apt sources"
  template: 
   src: "roles/common/templates/sources.list"
   dest: "/etc/apt/sources.list"

- name: "Uninstall slapd"
  apt: 
   name: "slapd" 
   state: "absent" 
   purge: "yes"
   autoclean: yes
   autoremove: yes
  when: "cleanup is defined"

- name: "Remove OpenLDAP dirs"
  file: 
   path: "{{ item }}"
   state: "absent"
  with_items:
   - "/run/slapd"
   - "/etc/init.d/slapd"
   - "/etc/default/slapd"
   - "/var/log/slapd"
  when: "cleanup is defined"

- name: "Uninstall Shibboleth SP"
  apt: 
   name: "{{ item }}" 
   state: "absent"
   purge: "yes"
   autoclean: yes
   autoremove: yes
  with_items:
   - "libapache2-mod-shib2"
   - "shibboleth-sp2-common"
   - "shibboleth-sp2-utils"
  when: "cleanup is defined"

- name: "Remove Shibboleth SP files"
  file: 
   path: "{{ item }}"
   state: "absent"
  with_items:
   - "/etc/init.d/shibd"
   - "/etc/shibboleth"
   - "/etc/apache2/mods-available/shib2.load"
   - "/etc/default/shibd"
   - "/var/log/shibboleth"
   - "/var/lib/dpkg/info/shibboleth-sp2-utils.postrm"
   - "/var/lib/dpkg/info/shibboleth-sp2-utils.list"
   - "/var/lib/dpkg/info/shibboleth-sp2-common.list"
   - "/var/lib/apache2/module/disabled_by_maint/shib2"
  when: "cleanup is defined"

- name: "Check the existance of 'shibboleth' database"
  command: mysql -u root -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='shibboleth'"
  register: shib_db
  changed_when: false
  when: "cleanup is defined"

- name: "Remove 'shibboleth' database"
  shell: "mysql -e 'DROP DATABASE shibboleth'"
  when: 
   - "cleanup is defined"
   - "shib_db.stdout == 'shibboleth'"

- name: "Remove Shibboleth IdP files"
  file: 
   path: "{{ item }}"
   state: "absent"
  with_items:
   - "/opt/shibboleth-idp"
   - "/opt/shibboleth-identity-provider-3.3.2.tar.gz"
  when: "cleanup is defined"

- name: "Install apt packages"
  apt: 
   name: "{{ item }}"
   update_cache: "yes"
   state: "latest"
   install_recommends: "no"
  with_items:
    - html2text
    - vim
    - ntp
    - libmysql-java
    - ca-certificates
    - ssl-cert
    - openssl
    - curl
  tags: online

- name: "Install CA Certificate"
  copy: 
   src: "roles/common/files/cacert.pem"
   dest: "/etc/ssl/certs/cacert.pem"

- name: "Install CA Key"
  copy: 
   src: "roles/common/files/cakey.pem"
   dest: "/etc/ssl/private" 
   mode: "0600"

- name: "Install IdP Certificate"
  copy: 
   src: "roles/common/files/idp.example.org-cert.pem"
   dest: "/etc/ssl/certs/idp.example.org-cert.pem"

- name: "Install IdP Key"
  copy: 
   src: "roles/common/files/idp.example.org-key.pem" 
   dest: "/etc/ssl/private/idp.example.org-key.pem" 
   group: "ssl-cert" 
   mode: "0640"

- name: "Install SP Certificate"
  copy: 
   src: "roles/common/files/sp.example.org-cert.pem" 
   dest: "/etc/ssl/certs/sp.example.org-cert.pem"

- name: "Install SP Key"
  copy: 
   src: "roles/common/files/sp.example.org-key.pem" 
   dest: "/etc/ssl/private/sp.example.org-key.pem" 
   group: "ssl-cert"
   mode: "0640"
