---
# Install OpenJDK on Debian

- name: "Debian 8 - Add OpenJDK 8 backports APT repository"
  apt_repository:
    repo: "deb http://mi.mirror.garr.it/mirrors/debian/ jessie-backports main"
    state: present
    update_cache: "yes"
    filename: 'jessie-backports'

- name: "Install OpenJDK 8"
  apt:
   name: "{{ item }}"
   state: latest
   default_release: "jessie-backports"
   install_recommends: "no"
  with_items:
   - "ca-certificates-java"
   - "openjdk-8-jre-headless"
   - "openjdk-8-jre"
   - "openjdk-8-jdk"

- name: "Configure default-java link"
  file:
   src: "/usr/lib/jvm/java-8-openjdk-amd64"
   dest: "/usr/lib/jvm/default-java"
   state: link
